version: '3.9'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  nodejs:
    image: node:8
    build: gate-simulator
    ports:
      - '9999:9999'


